version: '3'
services:

 # FastAPI App 
  app:
    container_name: app
    build: 
      context: ./app
      dockerfile: Dockerfile  
    command: >
      sh -c "python3 main.py"
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - custom

  scheduler:
    container_name: scheduler
    depends_on:
      - nginx
    build: 
      context: ./scheduler
      dockerfile: Dockerfile  
    command: >
      sh -c "python3 main.py"
    env_file:
      - .env
    volumes:
      - ./scheduler:/scheduler
    expose:
      - 8010
    networks:
      - custom

 # Mongo Database 
  mongo_db:
    image: mongo
    container_name: mongo_db
    env_file:
      - .env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - custom
 

  # Postgres Database 
  postgres_db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    networks:
      - custom


  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - custom  


networks:
  custom:
    driver: bridge